#define _POSIX_C_SOURCE 200809L
#include "../common/protocol.h"
#include <arpa/inet.h>
#include <errno.h>
#include <netinet/in.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/socket.h>
#include <unistd.h>

enum { WIDTH = 920, HEIGHT = 600, STRIDE = WIDTH * 4 };
struct agent { int fd; bool hello, created, full, damage, destroyed; uint8_t *fb; uint64_t frame; uint64_t wire; uint32_t damage_count; };
static void fail(const char *s) { fprintf(stderr, "FAIL: stage7b-agent: %s\n", s); exit(1); }
static bool send_all(int fd, const uint8_t *p, size_t n) { while (n) { ssize_t r = send(fd,p,n,0); if (r > 0) { p += r; n -= (size_t)r; } else if (r < 0 && errno == EINTR) continue; else return false; } return true; }
static bool send_msg(struct agent *a, uint16_t t, const uint8_t *p, uint32_t n) { CwBuffer b; bool ok; cw_buffer_init(&b); ok = cw_message_encode(&b,t,0,a->wire++,p,n) && send_all(a->fd,b.data,b.length); cw_buffer_destroy(&b); return ok; }
static bool pixel(const struct agent *a, int x, int y, uint8_t b, uint8_t g, uint8_t r, uint8_t al) { const uint8_t *p = a->fb + (size_t)y * STRIDE + (size_t)x * 4; if (p[0] != b || p[1] != g || p[2] != r || p[3] != al) fprintf(stderr,"pixel[%d,%d]=%u,%u,%u,%u expected=%u,%u,%u,%u\n",x,y,p[0],p[1],p[2],p[3],b,g,r,al); return p[0] == b && p[1] == g && p[2] == r && p[3] == al; }
static bool apply_damage(struct agent *a, const CwWindowDamage *d) { CwDamageRect rs[CW_MAX_DAMAGE_RECTS]; uint32_t i; if (d->window_id != 1 || d->base_frame_sequence != a->frame) return false; for (i=0;i<d->rect_count;i++) { uint32_t row; if (!cw_window_damage_rect_at(d,i,&rs[i]) || rs[i].x < 0 || rs[i].y < 0 || (uint64_t)rs[i].x+rs[i].width > WIDTH || (uint64_t)rs[i].y+rs[i].height > HEIGHT) return false; for(row=0;row<rs[i].height;row++) memcpy(a->fb + ((size_t)rs[i].y+row)*STRIDE + (size_t)rs[i].x*4, rs[i].pixels + (size_t)row*rs[i].stride, rs[i].stride); } a->frame=d->frame_sequence; return true; }
static bool on_msg(void *ctx, const CwHeader *h, const uint8_t *p) { struct agent *a=ctx; if(h->type==CW_MESSAGE_HELLO_ACK){ CwHelloAck x; if(!cw_decode_hello_ack(p,h->payload_length,&x)||x.selected_version!=CW_PROTOCOL_VERSION)return false; a->hello=true;return true; } if(h->type==CW_MESSAGE_OUTPUT_CONFIG){ CwOutputConfig x; return a->hello&&cw_decode_output_config(p,h->payload_length,&x)&&x.scale_numerator==1U&&x.scale_denominator==1U; } if(h->type==CW_MESSAGE_WINDOW_CREATE){ CwWindowCreate x; if(!a->hello||!cw_decode_window_create(p,h->payload_length,&x)||x.window_id!=1||x.surface_width!=WIDTH||x.surface_height!=HEIGHT)return false; a->fb=calloc(1,(size_t)STRIDE*HEIGHT); a->created=a->fb!=NULL;return a->created; } if(h->type==CW_MESSAGE_WINDOW_FRAME){ CwWindowFrame x; if(!a->created||!cw_decode_window_frame(p,h->payload_length,&x)||x.width!=WIDTH||x.height!=HEIGHT||x.stride!=STRIDE||x.pixel_bytes!=(uint64_t)STRIDE*HEIGHT)return false; memcpy(a->fb,x.pixels,(size_t)x.pixel_bytes);a->frame=x.frame_sequence;a->full=true;return pixel(a,100,100,0x20,0x30,0x60,255)&&pixel(a,900,100,0x10,0x40,0xb0,255)&&pixel(a,50,210,16,24,176,255); } if(h->type==CW_MESSAGE_WINDOW_DAMAGE){ CwWindowDamage x; if(!cw_decode_window_damage(p,h->payload_length,&x)||!apply_damage(a,&x))return false;a->damage=true;a->damage_count++;return a->damage_count==1U?pixel(a,50,210,16,152,48,255):a->damage_count==2U?pixel(a,50,210,0x20,0x30,0x60,255):false; } if(h->type==CW_MESSAGE_WINDOW_PRESENT){ CwWindowPresent x;uint8_t ack[16];if(!cw_decode_window_present(p,h->payload_length,&x)||!a->full)return false;cw_store_u64_le(ack,x.window_id);cw_store_u64_le(ack+8,x.presentation_sequence);return send_msg(a,CW_MESSAGE_WINDOW_PRESENT_ACK,ack,16); } if(h->type==CW_MESSAGE_WINDOW_ACTIVATE){ CwWindowActivate x;return a->created&&cw_decode_window_activate(p,h->payload_length,&x)&&x.window_id==1U; } if(h->type==CW_MESSAGE_WINDOW_DESTROY){if(!a->full||!a->damage||a->damage_count!=2U||h->payload_length!=8)return false;a->destroyed=true;return true;} return false; }
int main(int argc,char **argv) { struct agent a={.fd=-1,.wire=1};struct sockaddr_in ad={.sin_family=AF_INET};CwDecoder d;uint8_t hello[8]={0},buf[8192];long port=44610;char *end;if(argc==2){port=strtol(argv[1],&end,10);if(*end||port<1||port>65535)fail("usage");}else if(argc!=1)fail("usage");ad.sin_port=htons((uint16_t)port);inet_pton(AF_INET,"127.0.0.1",&ad.sin_addr);a.fd=socket(AF_INET,SOCK_STREAM,0);if(a.fd<0||connect(a.fd,(struct sockaddr*)&ad,sizeof(ad))<0)fail("connect");cw_store_u16_le(hello,CW_PROTOCOL_VERSION);cw_store_u16_le(hello+2,CW_PROTOCOL_VERSION);cw_store_u32_le(hello+4,CW_PIXEL_FORMAT_MASK_BGRA8888);if(!send_msg(&a,CW_MESSAGE_HELLO,hello,8))fail("hello");cw_decoder_init(&d);while(!a.destroyed){ssize_t n=recv(a.fd,buf,sizeof(buf),0);if(n<=0||!cw_decoder_feed(&d,buf,(size_t)n,on_msg,&a))fail("receive/decode");}cw_decoder_destroy(&d);free(a.fb);close(a.fd);puts("stage7b subsurface/alpha integration: PASS");return 0;}
